### ISSUE TITLE
Website Publishing Roadmap

### ISSUE THREAD

**Issue by 3manuek** [babelfish-for-postgresql/babelfish_project_website#3]
- [x] Create single repo for Project website
- [x] Move existing assets to this repo.
- [x] #6
   - OpenSearch has created 2 repos one for website and the other for documentation. I don't see a need to have 2 separate repos. We need one single repo for Project Website and Project Documentation. Merge the repos into one i.e.o   
   - Project Website Repo https://github.com/opensearch-project/project-website
   - Documentation Repo https://github.com/opensearch-project/documentation-website/tree/main/_search-plugins/knn
   - Checkpoint 1: (WAS) Sept 13th. Have a repo with the Open Search assets (documentation/blog entries) removed and with Babelfish images. Have this working locally. 
   - Target: Friday, (WAS) September 10th. 

- [x] Move documentation
   - Move existing documentation
   - Review documentation 
   - Document the process of adding documentation to the project.

- [x] Setup the Jekyll pipeline and publish website with Babelfish text (Overview and Guiding Principles )
     - Build a testing workflow
     - Configure workflow
     - Test workflow
     - Replace landing page text with those provided for Babelfish by Gopi. Ensure existing links to documentation, github repo are all disabled.
     - Create the pipeline to publish the website to existing github pages https://babelfish-for-postgresql.github.io/babelfish-for-postgresql/
     - Ensure website isn't published to live website until go-live date.

- [x] Going live

- [x] Create go-live / maintenance documentation and future maintenance and the process to publish in the future. 
   
- OnGres
  - [x] Checkpoint 2: WAS Sept 16th. Publish the website, replacing the current GH pages site. Target: Tuesday, September N th.
